# Copy this to your Streamlit Cloud secrets
gcp_project_id = "ai-market-trend-advisor"

[gcp_service_account]
type = "service_account"
project_id = "ai-market-trend-advisor"
private_key_id = "YOUR_ACTUAL_KEY_ID"
private_key = "-----BEGIN PRIVATE KEY-----\nYOUR_ACTUAL_PRIVATE_KEY\n-----END PRIVATE KEY-----\n"
client_email = "your-service-account@ai-market-trend-advisor.iam.gserviceaccount.com"
client_id = "YOUR_ACTUAL_CLIENT_ID"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "YOUR_ACTUAL_CERT_URL"
