gcp_project_id = "ai-market-trend-advisor"
[gcp_service_account]
type = "service_account"
project_id = "ai-market-trend-advisor"
private_key_id = "7aa33303e247b1ef57d7462169887cc8483f7ac2"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCfEumJslNL+VoL\nDCDjnkvwALcDyYHU113sa66XxJ2+91NKai4hJP4smofN4V3VGOeVQZc9pDaU3nJU\nd9T6atZUcOZIBuK68hL5d[...]"
client_email = "331265891123-compute@developer.gserviceaccount.com"
client_id = "115473117176637194370"
token_uri = "https://oauth2.googleapis.com/token"
